# Generated by Django 4.2 on 2023-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_menu", "0002_remove_menu_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu", name="is_main", field=models.BooleanField(default=False),
        ),
    ]
