# Generated by Django 4.2 on 2023-04-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tree_menu", "0003_menu_is_main"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="is_main",),
    ]
